# Generated by Django 3.0.7 on 2020-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='light2_status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
